// Frozen, cold-query qualification fixture for the swept circular filter modes.
// The ray bank is constructed without inspecting any query result.
#include "stellarcsg/compiled_swept_surface.hpp"

#include <cfenv>
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
using stellarcsg::Vec3;
constexpr double pi = 3.1415926535897932384626433832795;

struct FrozenRay {
  Vec3 origin;
  Vec3 direction;
  const char* category;
  bool transformed {false};
  bool coincident {false};
};

stellarcsg::SweptSplineSurfaceData fixture()
{
  stellarcsg::SweptSplineSurfaceData data;
  data.coil_id = 71;
  data.sample_count = 64;
  data.length = 10*pi;
  data.characteristic_length = 9;
  data.major_radius_coefficients.assign(data.sample_count, .25);
  data.minor_radius_coefficients.assign(data.sample_count, .25);
  for (std::size_t i = 0; i < data.sample_count; ++i) {
    const double q = 2*pi*static_cast<double>(i)/data.sample_count;
    for (double value : {5*std::cos(q), 5*std::sin(q), .4*std::sin(3*q)})
      data.centerline_coefficients.push_back(value);
    for (double value : {0., 0., 1.}) data.normal_coefficients.push_back(value);
    for (double value : {1., 0., 0.}) data.binormal_coefficients.push_back(value);
  }
  return data;
}

Vec3 knot(const stellarcsg::SweptSplineSurfaceData& data, std::size_t i)
{
  Vec3 value;
  for (int offset = -1; offset <= 1; ++offset) {
    const auto n = static_cast<long>(data.sample_count);
    const auto index = static_cast<std::size_t>((static_cast<long>(i) + offset + n) % n);
    const double weight = offset == 0 ? 4./6 : 1./6;
    value += weight*Vec3 {data.centerline_coefficients[3*index],
      data.centerline_coefficients[3*index + 1], data.centerline_coefficients[3*index + 2]};
  }
  return value;
}

Vec3 rotate(Vec3 p) { return {0.6*p.x - 0.8*p.z, p.y, 0.8*p.x + 0.6*p.z}; }

stellarcsg::SweptSplineSurfaceData transformed_fixture(
  const stellarcsg::SweptSplineSurfaceData& source)
{
  auto result = source;
  const Vec3 translation {11, -7, 3};
  for (std::size_t i = 0; i < result.sample_count; ++i) {
    for (auto* values : {&result.centerline_coefficients, &result.normal_coefficients,
           &result.binormal_coefficients}) {
      Vec3 value {(*values)[3*i], (*values)[3*i + 1], (*values)[3*i + 2]};
      value = rotate(value);
      if (values == &result.centerline_coefficients) value += translation;
      (*values)[3*i] = value.x;
      (*values)[3*i + 1] = value.y;
      (*values)[3*i + 2] = value.z;
    }
  }
  return result;
}

std::vector<FrozenRay> frozen_bank(const stellarcsg::SweptSplineSurfaceData& data)
{
  // Six categories are intentionally generated by geometry alone.  Every
  // generated ray is retained even if a future kernel rejects or misses it.
  std::vector<FrozenRay> rays;
  rays.reserve(64);
  for (int i = 0; i < 12; ++i) {
    const double y = -9.0 + 18.0*i/11.0;
    rays.push_back({{-10., y, 4.}, {-1., .031*(i + 1), .02}, "bbox_miss"});
  }
  for (int i = 0; i < 12; ++i) {
    // z=.64 lies inside the conservative global box (the tube bound reaches
    // .65) but outside the local tube near the x-axis crossings.
    rays.push_back({{-8. - .01*i, 0., .64}, {1., .0001*(i + 1), 0.},
      "bbox_intersect_physical_miss"});
  }
  for (int i = 0; i < 12; ++i) {
    const Vec3 c = knot(data, static_cast<std::size_t>(i*5 % 64));
    rays.push_back({c + Vec3 {.252, .003*(i - 6), .002*(i % 3)},
      {-1., .01*(i - 5), .003}, "near_normal_entry"});
  }
  for (int i = 0; i < 10; ++i) {
    const Vec3 c = knot(data, static_cast<std::size_t>((i*7 + 3) % 64));
    rays.push_back({c, {std::cos(.37*i), std::sin(.37*i), .2}, "inside_exit"});
  }
  for (int i = 0; i < 10; ++i) {
    const Vec3 c = knot(data, static_cast<std::size_t>((i*6) % 64));
    const double offset = (i - 5)*1.e-10;
    rays.push_back({c + Vec3 {-2., .25 + offset, 0.}, {1., 0., 0.}, "seam_grazing"});
  }
  const Vec3 translation {11, -7, 3};
  for (int i = 0; i < 8; ++i) {
    const Vec3 c = knot(data, static_cast<std::size_t>((i*8 + 1) % 64));
    rays.push_back({rotate(c + Vec3 {.252, .002*i, 0.}) + translation,
      rotate({-1., .01*i, 0.}), "rigid_transform", true});
  }
  if (rays.size() != 64) throw std::logic_error("frozen bank cardinality drift");
  // Interleave categories so the bounded 8/16-ray cold pilots retain broad
  // misses, physical misses, crossings, tangencies, and rigid transforms.
  std::vector<FrozenRay> interleaved;
  interleaved.reserve(rays.size());
  constexpr std::size_t starts[] {0, 12, 24, 36, 46, 56};
  constexpr std::size_t sizes[] {12, 12, 12, 10, 10, 8};
  for (std::size_t round = 0; interleaved.size() != rays.size(); ++round)
    for (std::size_t category = 0; category < 6; ++category)
      if (round < sizes[category]) interleaved.push_back(rays[starts[category] + round]);
  return interleaved;
}

void vector_json(const Vec3& value)
{
  std::cout << '[' << value.x << ',' << value.y << ',' << value.z << ']';
}

void diagnostics_json(const stellarcsg::RootSearchDiagnostics& value)
{
  std::cout << "{\"floating_excluded_spans\":" << value.floating_excluded_spans
    << ",\"polynomial_excluded_spans\":" << value.polynomial_excluded_spans
    << ",\"exact_candidate_spans\":" << value.exact_candidate_spans
    << ",\"monotone_attempted_spans\":" << value.monotone_attempted_spans
    << ",\"monotone_resolved_spans\":" << value.monotone_resolved_spans
    << ",\"sturm_fallback_spans\":" << value.sturm_fallback_spans
    << ",\"certified_excluded_intervals\":" << value.certified_excluded_intervals
    << ",\"subdivided_intervals\":" << value.subdivided_intervals;
#ifdef STELLARCSG_ENABLE_PERFORMANCE_COUNTERS
  std::cout << ",\"exact_candidate_nanoseconds\":" << value.exact_candidate_nanoseconds;
  std::cout << ",\"exact_query_nanoseconds\":" << value.exact_query_nanoseconds;
  std::cout << ",\"monotone_nanoseconds\":" << value.monotone_nanoseconds;
  std::cout << ",\"sturm_nanoseconds\":" << value.sturm_nanoseconds;
#endif
  std::cout << '}';
}

void result_json(const stellarcsg::DistanceResult& value, long long nanoseconds)
{
  std::cout << "\"found\":" << (value.found ? "true" : "false")
    << ",\"distance\":";
  if (value.found && std::isfinite(value.distance)) std::cout << value.distance;
  else std::cout << "null";
  std::cout << ",\"residual\":";
  if (value.found && std::isfinite(value.residual)) std::cout << value.residual;
  else std::cout << "null";
  std::cout << ",\"root_kind\":" << static_cast<int>(value.kind)
    << ",\"solver_path\":" << static_cast<int>(value.root_diagnostics.solver_path)
    << ",\"fallback_reason\":" << static_cast<int>(value.root_diagnostics.fallback_reason)
    << ",\"state\":\"OK\""
    << ",\"diagnostics\":";
  diagnostics_json(value.root_diagnostics);
  if (nanoseconds >= 0) std::cout << ",\"ns\":" << nanoseconds;
}

bool same_result(const stellarcsg::DistanceResult& left,
  const stellarcsg::DistanceResult& right)
{
  if (left.found != right.found || left.kind != right.kind
      || left.root_diagnostics.solver_path != right.root_diagnostics.solver_path
      || left.root_diagnostics.fallback_reason != right.root_diagnostics.fallback_reason) return false;
  return !left.found || (std::isfinite(left.distance) && std::isfinite(right.distance)
    && std::abs(left.distance - right.distance) <= 2.e-8
    && std::abs(left.residual - right.residual) <= 2.e-8);
}

void require(bool condition, const char* label)
{
  if (!condition) throw std::runtime_error(label);
}

void focused_controls(const stellarcsg::CompiledSweptSplineSurface& coil,
  const stellarcsg::SweptSplineSurfaceData& data)
{
  const Vec3 c = knot(data, 0);
  const auto unit = coil.distance(c + Vec3 {.252, 0, 0}, {-1, 0, 0}, false);
  for (double scale : {3., 1.e-200, 1.e200})
    require(same_result(unit, coil.distance(c + Vec3 {.252, 0, 0}, {-scale, 0, 0}, false)),
      "non-unit direction control");
  const auto first = coil.distance(c + Vec3 {.252, .031, .017}, {-1, 0, 0}, false);
  require(first.found, "finite entry control");
  const Vec3 rounded = c + Vec3 {.252, .031, .017} + first.distance*Vec3 {-1, 0, 0};
  const auto advanced = coil.distance(rounded, {-1, 0, 0}, true);
  require(advanced.found && advanced.distance > .4, "next boundary control");
  const auto nudged = coil.distance({std::nextafter(rounded.x, std::numeric_limits<double>::infinity()),
    rounded.y, rounded.z}, {-1, 0, 0}, true);
  require(nudged.found, "nextafter coincidence control");
  bool rejected = false;
  try { (void)coil.distance({100, 0, 0}, {1, 0, 0}, true); }
  catch (const std::exception&) { rejected = true; }
  require(rejected, "missing coincidence association control");
  const int saved = std::fegetround();
  if (std::fesetround(FE_UPWARD) == 0) {
    const auto upward = coil.distance(c + Vec3 {.252, 0, 0}, {-1, 0, 0}, false);
    require(same_result(unit, upward), "FE_UPWARD bypass control");
    std::fesetround(saved);
  }
}
}

int main(int argc, char** argv)
{
  int mode = 2, count = 8, repeats = 1;
  bool profile = false, skip_controls = false;
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    const auto value = [&](const char* flag) -> const char* {
      if (++i >= argc) throw std::invalid_argument(std::string("missing value for ") + flag);
      return argv[i];
    };
    if (arg == "--mode") mode = std::stoi(value("--mode"));
    else if (arg == "--count") count = std::stoi(value("--count"));
    else if (arg == "--repeats") repeats = std::stoi(value("--repeats"));
    else if (arg == "--profile") profile = true;
    else if (arg == "--skip-controls") skip_controls = true;
    else throw std::invalid_argument("unknown option: " + arg);
  }
  if (mode < 0 || mode > 2 || count < 1 || count > 64 || repeats != 1)
    throw std::invalid_argument("mode is 0..2, count is 1..64, repeats must be 1");
  std::cout << std::setprecision(17);
  const auto data = fixture();
  const auto rigid = transformed_fixture(data);
  const stellarcsg::CompiledSweptSplineSurface coil(data, true), transformed(rigid, true);
  const auto bank = frozen_bank(data);
  int failures = 0, blocked = 0;
  if (!skip_controls) {
    try { focused_controls(coil, data); }
    catch (const std::exception& error) { ++failures; std::cerr << "CONTROL_FAIL " << error.what() << '\n'; }
  }
  for (int index = 0; index < count; ++index) {
    const auto& ray = bank[static_cast<std::size_t>(index)];
    stellarcsg::RootSearchOptions options;
    options.circular_filter_mode = mode;
    try {
      stellarcsg::DistanceResult result;
      long long ns = -1;
      const auto begin = std::chrono::steady_clock::now();
      result = (ray.transformed ? transformed : coil).distance(ray.origin, ray.direction,
        ray.coincident, options);
      const auto end = std::chrono::steady_clock::now();
      if (profile) ns = std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin).count();
      std::cout << "{\"kind\":\"ray\",\"index\":" << index << ",\"category\":\""
        << ray.category << "\",\"origin\":";
      vector_json(ray.origin);
      std::cout << ",\"direction\":"; vector_json(ray.direction);
      std::cout << ",\"coincident\":" << (ray.coincident ? "true" : "false")
        << ",\"transformed\":" << (ray.transformed ? "true" : "false")
        << ",\"mode\":" << mode << ',';
      result_json(result, ns);
      std::cout << "}\n";
    } catch (const std::exception& error) {
      ++blocked;
      std::cout << "{\"kind\":\"ray\",\"index\":" << index << ",\"category\":\""
        << ray.category << "\",\"origin\":";
      vector_json(ray.origin);
      std::cout << ",\"direction\":"; vector_json(ray.direction);
      std::cout << ",\"coincident\":" << (ray.coincident ? "true" : "false")
        << ",\"transformed\":" << (ray.transformed ? "true" : "false")
        << ",\"mode\":" << mode
        << ",\"found\":false,\"distance\":null,\"residual\":null,\"state\":\"BLOCKED\"}\n";
      std::cerr << "BLOCKED ray=" << index << " error=" << error.what() << '\n';
    }
  }
  std::cout << "{\"kind\":\"summary\",\"mode\":" << mode << ",\"count\":" << count
    << ",\"repeats\":" << repeats << ",\"profile\":" << (profile ? "true" : "false")
    << ",\"controls_skipped\":" << (skip_controls ? "true" : "false")
    << ",\"failures\":" << failures << ",\"blocked\":" << blocked << "}\n";
  return failures ? 1 : blocked ? 2 : 0;
}
